main: dev.tomwmth.exampleplugin.ExamplePlugin
name: ExamplePlugin
version: ${version}
description: An example plugin using AlpineCore
author: tomwmth
website: https://github.com/tomwmth
api-version: 1.13

depend:
  - AlpineCore

softdepend:
  - ViaVersion